### ISSUE TITLE
License

### ISSUE THREAD

**Issue by niklaskorz** [pedrohenriquerls/libvim_rs#1]
I am writing a code editor as a sideproject at https://github.com/niklaskorz/lyranos, based on druid and tree-sitter, and I might be interested in adding a vim mode based on your libvim bindings. Any thoughts under what license the bindings could be released? As libvim itself is MIT licensed, I guess it might make the most sense to go with the same. Also, if you have interest in collaborating, I'd be glad to help out!

**Comment by pedrohenriquerls** [comment]
@niklaskorz sorry to take so long to answer your issue.
Yes, I'm planning to have it under MIT license.

**Comment by pedrohenriquerls** [comment]
https://github.com/pedrohenriquerls/libvim_rs/commit/90960c21fc0a30e1c4def618472536f0847acb3a
